### ISSUE TITLE
skip UMITOOLS_PREPAREFORRSEM process if RSEM is not used

### ISSUE THREAD

**Issue by julienlag** [Flomics/rnaseq#49]
### Description of feature

it sometimes consumes a lot of resources

**Comment by ctuni** [comment]
Branch `feature/skip_prepareforrsem` created and updated, will test it tomorrow

**Comment by lcabus-flomics** [comment]
Let me know how it went and if I have to do anything

**Comment by ctuni** [comment]
I'll test it now and if it works (the process is skiped) I'll create a pull request and ask you for review!

**Comment by lcabus-flomics** [comment]
I have merged the results to the dev branch, so it should be solved now

**Comment by ctuni** [comment]
When process is skiped a warning still appears with the following message:
`WARN: There's no process matching config selector: NFCORE_RNASEQ:RNASEQ:UMITOOLS_PREPAREFORRSEM` 

I think we should make sure this message does not appear, I'll check how to "fix" it since it's only a warning and it does not affect the run in any way.

**Comment by julienlag** [comment]
> When process is skiped a warning still appears with the following message: `WARN: There's no process matching config selector: NFCORE_RNASEQ:RNASEQ:UMITOOLS_PREPAREFORRSEM`
> 
> I think we should make sure this message does not appear, I'll check how to "fix" it since it's only a warning and it does not affect the run in any way.

I think this is due to the process name being present in the config file, it's perfectly normal. The message will disappear as soon as the corresponding process entry is removed from the config

**Comment by julienlag** [comment]
We need to 
- understand how this change made it to the production pipeline
- implement a set of robust tests so that it doesn't happen again in the future
